version: '3.9'
services:
  suggestions:
    build:
      context: .
    container_name: 'suggestions'
    hostname: suggestions
    env_file:
      - .env
    networks:
      - main

networks:
  main:
    external: true